services:
  db:
    image: postgres:16
    container_name: dr_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: durdona56
      POSTGRES_DB: durdona2  # default db
    ports:
      - "5497:5432"
    volumes:
      - baza_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: durdon_bot
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        pnpm run build &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        pnpm run start:dev
      "

volumes:
  baza_data:
